### ISSUE TITLE
论文中的一些疑惑

### ISSUE THREAD

**Issue by HelloMX** [wuhuikai/FastFCN#6]
按照论文中3.3.3 开头所说的流程  应该通过ys和ym0来学习得到h
但是3.3.3中并没有讲如何得到ys？

论文中说将3个尺度的特征图上采样，请问是怎样上采样的？
通过h来进行联合上采样又是具体怎么学习的？

看论文从3.3.3开始就感觉具体操作和前面的内容有点接不上了

**Comment by wuhuikai** [comment]
1. `y_s` 是没有`dilated convolution`的`backbone`的输出, 即经典`FCN`的`backbone`的输出
2. `h`是通过一个`CNN` (即`JPU`) 建模的。具体来说，`JPU`是在进行如下操作: (1)求解出一个隐式的`h`, (2)使用隐式的`h`来处理`y_m`, 获得最后上采样后的特征图

**Comment by HolmesShuan** [comment]
Hi, SOTA with 3x speedup. Nice job!
Due to my limited knowledge of segmentation, I find the following descriptions hard to understand, any help?
1. The caption of Figure 5: `... and the rest part of y_m`.  What do you mean the `rest part`?
2.  The right subfigure of Figure 5 wraps node 1,2,3 with `3x3 conv, d=1`, yet left subfigure uses node 0,2,4. Note that `dilation rate 1 focuses on y^0_m`, which corresponds to the left subfigure or the other? How to understand `dilation rate 1 focuses on y^0_m` and `d=2 aims at y^0_m and y_s`?
3. The problem defined in Eq.(1): is ![equation](http://latex.codecogs.com/gif.latex?f(\cdot)) a known function? If it is true, Eq.(4) with learnable ![equation](http://latex.codecogs.com/gif.latex?h(\cdot)) and ![equation](http://latex.codecogs.com/gif.latex?\hat{h}(\cdot)) may be different from the pre-defined joint upsampling problem. 
4. As described in section 3.3.3, `Eq.(4) is an optimization problem`. What is the specific learning target in this problem? 

Thanks in advance.

**Comment by wuhuikai** [comment]
1. As shown in `Equation 4`, `y_m` can be split into `y_m^0` and `y_m^1`. The rest part of `y_m` means `y_m^1`.
2. Both `d=1` and `d=2` correspond to the right figure. The left figure shows that `y_s` only depends on `y_m^0`. The inputs of `d=1` (the dotted box) are `y_m^0` and `y_m^1`, while the inputs of `d=2` (the solid box) are `y_m^0`.
3. `f()` is a know function. As for `Equation 4`, `y_s = h(y_m^0)` is also a know function after the training converges.
4. The objective is to find a function `\hat{h}()` to approximate `y_s = h(y_m^0)`.

**Comment by HolmesShuan** [comment]
Thanks for your responses. I still wonder the proposed `solving with CNNs` indeed solves the optimization problem **strictly**? The stage (b) seems to optimize ![equation](http://latex.codecogs.com/gif.latex?h(\cdot)) and ![equation](http://latex.codecogs.com/gif.latex?\hat{h}(\cdot)) simultaneously.

**Comment by wuhuikai** [comment]
`JPU` does **not** solve the optimization problem strictly. Motivated by joint upsampling, we employ a `CNN` to approximate the optimization problem.

**Comment by HolmesShuan** [comment]
Cool, thanks.
